### ISSUE TITLE
HRGS : la fatigue qui tiens à peine 10 minutes

### ISSUE THREAD

**Issue by stephanepapin** [davidou2a/HellRetex_Official#100]
Bonjour.

J'ai un soucis depuis la dernière mise à jour avec la fatigue qui tiens à peine (edit) **6 minutes** en courses alors que j'ai de configuré : 28800 dans le JSON.

Je me demande si cela n'est pas lié à l'accélération de temps du serveur (x12 de jour).
Mon Json :
```
{
    "UseMedicalReport": 1,
    "EnableRestrictionBackpack": 0,
    "EnableZombification": 0,
    "ZombificationHitValue": 100.0,
    "EnableSoftSkills": 0,
	"MinutesBeforeNewSoftSkillPoint": 10.0,
    "CleaningGainByUsingWipes": 10.0,
    "TirednessDuration": 28800.0,
    "DirtynessDuration": 28800.0,
    "SoapItems": [],
    "HeadgearConsumeRestrictionItems": [],
    "MaskConsumeRestrictionItems": [],
    "DietGoodFoodLevelOne": [],
    "DietGoodFoodLevelTwo": [],
    "DietBadFoodLevelOne": [],
    "DietBadFoodLevelTwo": []
}
```
@+

**Comment by SilverOcircle** [comment]
Unfortunately I have to report the same. Now I'm getting tired, but it all happens within 10 minutes.

**Comment by RSJFL** [comment]
Unfortunately I have to report the same too. I'm getting tired, but it all happens within 10 minutes.
Tiredness indicator is set to 25000.0

**Comment by MATTvanEAGLE** [comment]
I have to contribute the same with the HREG Evolution, todays update didn't fix this issue. Indicator is set to 14400.0 in our EnhancedGameplay_ServerSettings.json but tiredness reduces to minimum within around 10 minutes.

**Comment by davidou2a** [comment]
I will post this message to clarify the situation :
- **No, there is no bug**, the bug was fixed and was present since 2 or 3 updates.

Below a video of my test with the current version of HREG (*Stable & Evo are same at this time*)

I have just unlock the time limit to set 120 seconds (2mins) and show to you this video.
You can see i have set 120 in the JSON, __for remind it's 120 for only jogging__, never sprint,climb, climb ladder, or vaulting, this value is only based on jog movement ! **sprint is more consumer**...

Your players should change their behavior with **this mod, isnt a mod for "Loot&Run" style or for those who run always in front of infected**. This video is a proof, within 2min you are out of resting level.

***For player who have an issue with a tiredness faster empty, just try just to respawn with a fresh player.***

Regards, and play safe !

https://www.youtube.com/watch?v=POPAzDa4We0
